name: SyncEngine
main: com.kamikazejam.syncengine.SyncEnginePlugin
version: ${version}
authors: [KamikazeJAM]
website: https://github.com/Jake-Moore/SyncEngine
description: ${description}
api-version: 1.13
depend:
  - KamiCommon